apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pvName }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pvStorage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ template "name" . }}.{{ .Values.namespace }}.svc.cluster.local
    path: "/"
