apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    app: {{ template "name" . }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
#      serviceAccountName: nfs-service-account
      containers:
      - name: {{ .Values.nfsImage }}
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-local
      volumes:
        - name: nfs-local
          volumeClaimTemplates:
            metadata:
              name: nfs-local
              labels:
                chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
                release: {{ .Release.Name }}
                heritage: {{ .Release.Service }}
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: {{ .Values.localStorage | quote }}

