# docker images
image:
  akka: lightbend/fdp-ad-speculativemodelserver
  publisher: lightbend/fdp-ad-publisher
  trainingpublish: lightbend/trainingmodelpublish
  trainingingest: lightbend/trainingdataingestion
  trainingprocess: lightbend/amomaly-detection-intel-bigdl
  pullPolicy: Always
  version: 2.0.0
# Configuration parameters for an application
configuration:
  storage:
    localStorage: 1Gi
    storageshare: "/usr/data"
  kafka:
    brokerlist : "my-cluster-kafka-brokers.strimzi.svc:9092"
  grafana :
    host: "grafana.sample.svc"
    port: "80"
  influx :
    host : "influxdb.sample.svc"
    port : 8086
  statelistener :
    port : 5500
  publisher :
    data_publish_interval : "2 second"
  trainingdata :
    ingestion_interval : "10 minutes"
    ingestion_threshold_count : "1024"
    data_file_name : "/usr/data/CPU_examples.csv"
    generation_complete_file_name : "/usr/data/data_preparation_complete.txt"
    last_timestamp_file_name : "/usr/data/last_timestamp.txt"
    training_complete_file_name : "/usr/data/training_complete.txt"
    hyperparameters_file_name : "/usr/data/hyperparams.properties"
  publishingmodel :
    pbFileName: "/usr/data/model.pb"
    attributesFileName: "/usr/data/model-attributes.properties"
