image:
  __metadata:
    label: "Information about used images"
  akka:
    __metadata:
      label: "Application image for speculative model server"
      description: "Name of the speculative model server image"
      type: "string"
      required: true
  publisher:
    __metadata:
      label: "Publisher image"
      description: "Name of the loader image"
      type: "string"
      required: true
  pullPolicy:
    __metadata:
      label: "Image pull policy"
      description: "Image pull policy"
      type: "string"
      required: true
  version:
    __metadata:
      label: "Image version"
      description: "Image version should correspond to the FDP version"
      type: "string"
      required: true
configuration:
  __metadata:
    label: "Configuration parameters for running application"
  kafka:
    __metadata:
      label: "Kafka related configuration"
    brokerlist :
      __metadata:
        label: "List of brokers to connect to"
        description: "Coma separated list of brokers to connect to"
        type: "string"
        required: true
  grafana :
    __metadata:
      label: "Grafana related configuration"
    host :
      __metadata:
        label: "Grafana host"
        description: "Grafana host"
        type: "string"
        required: true
    port :
      __metadata:
        label: "Grafana port"
        description: "Grafana port"
        type: "integer"
        required: true
  influx :
    __metadata:
      label: "InfluxDB related configuration"
    host :
      __metadata:
        label: "InfluxDB host"
        description: "InfluxDB host"
        type: "string"
        required: true
    port :
      __metadata:
        label: "InfluxDB port"
        description: "InfluxDB port"
        type: "integer"
        required: true
  statelistener :
    __metadata:
      label: "Execution state listener"
    port :
      __metadata:
        label: "Listener port"
        description: "Listener port"
        type: "integer"
        required: true
  publisher :
    __metadata:
      label: "Publisher configuration"
    data_publish_interval :
      __metadata:
        label: "Data publish interval"
        description: "Data publish interval, for example 1 sec"
        type: "string"
        required: true
ingress:
  __metadata:
    label: "which ingress to use for exposing UI"
  type:
    __metadata:
      class: "Ingress class"
      description: "which Ingress class to use"
      type: "string"
      required: true
