apiVersion: v1
kind: Pod
metadata:
  name: speculativemodelserver
  labels:
    app: speculativemodelserver
spec:
  containers:
  - name: akkamodelserver
    image: {{ .Values.image.akka }}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - name: http
      containerPort: {{ .Values.configuration.statelistener.port}}
    env:
      - name: KAFKA_BROKERS_LIST
        value: {{ .Values.configuration.kafka.brokerlist}}
      - name: GRAFANA_HOST
        value: {{ .Values.configuration.grafana.host}}
      - name: GRAFANA_PORT
        value: "{{ .Values.configuration.grafana.port}}"
      - name: INFLUXDB_HOST
        value: {{ .Values.configuration.influx.host}}
      - name: INFLUXDB_PORT
        value: "{{ .Values.configuration.influx.port}}"
      - name: MODEL_SERVER_PORT
        value: "{{ .Values.configuration.statelistener.port}}"
---
apiVersion: v1
kind: Service
metadata:
  name: speculativemodelserver
spec:
  selector:
    app: speculativemodelserver
  ports:
  - protocol: TCP
    port: {{ .Values.configuration.statelistener.port}}
    targetPort: {{ .Values.configuration.statelistener.port}}

