apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: api
    port: {{ .Values.config.http.bind_address }}
    targetPort: {{ .Values.config.http.bind_address }}
  selector:
    app: {{ template "name" . }}