{{ if .Values.cassandraReaper.enableReaper }}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-reaper
  namespace: {{ .Release.Namespace }}
  labels:
    app: cassandra-reaper
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  REAPER_JMX_AUTH_PASSWORD: "{{ .Values.cassandraReaper.jmxAuth.password | b64enc }}"
{{ end }}