kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: support-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
users:
- system:serviceaccount:killrweather:nfs-service-account
- system:serviceaccount:killrweather:cassandra-service-account
- system:serviceaccount:killrweather:grafana-service-account
