apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fdp-taxiride-app
  labels:
    app: fdp-taxiride-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdp-taxiride-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdp-taxiride-app
    spec:
      containers:
      - name: taxirideapp
        image: {{ .Values.image.taxiride}}:{{.Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
          name: ui
        - containerPort: 6123
          name: rpc
    # Here we are running a local Flink server
        command:
        - sh
        - -c
        - "./bin/start-cluster.sh; ./bin/flink run  /opt/flink/examples/streaming/{{ .Values.taxiride.jar}} --broker-list {{ .Values.configuration.kafka.brokerlist}} --inTopic {{ .Values.configuration.kafka.intopic}} --outTopic {{ .Values.configuration.kafka.outtopic}}"
