apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fdp-taxiride-ingestion
  labels:
    app: fdp-taxiride-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdp-taxiride-ingestion
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fdp-taxiride-ingestion
    spec:
      containers:
      - name: taxirideingestion
        image: {{ .Values.image.ingestion}}:{{.Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: datadir
          mountPath: {{ .Values.data.directorytomatch }}
        env:
        - name: "DIRECTORY_TO_WATCH"
          value: {{ .Values.data.directorytomatch }}
        - name: "KAFKA_BROKERS"
          value: {{ .Values.configuration.kafka.brokerlist}}
      # These container runs during pod initialization
      initContainers:
      - name: install
        image: busybox
        command:
        - sh
        - -c
        - wget {{ .Values.data.datadirectory }} -O {{ .Values.data.directorytomatch }}/nycTaxiRides.csv.tgz; tar xvfz {{ .Values.data.directorytomatch }}/nycTaxiRides.csv.tgz -C {{ .Values.data.directorytomatch }}; ls -l {{ .Values.data.directorytomatch }}
        volumeMounts:
        - name: datadir
          mountPath: {{ .Values.data.directorytomatch }}
      dnsPolicy: Default
      volumes:
      - name: datadir
        emptyDir: {}
