zeppelin:
  image: apache/zeppelin:0.8.0
  resources:
    limits:
      memory: "4096Mi"
      cpu: "2000m"

hadoop:
  useConfigMap: false
  configMapName: hadoop-hadoop
  configPath: /usr/hadoop-2.7.3/etc/hadoop

spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2
