
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: killrweatherdataloader
  labels:
    app: killrweatherdataloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: killrweatherdataloader
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: killrweatherdataloader
    spec:
      containers:
      - name: killrweatherdataloader
        image: {{ .Values.image.loader}}:{{.Values.image.version }}
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: '{{ .Values.configuration.kafka.brokerlist}}'
        - name: PUBLISH_INTERVAL
          value: '{{ .Values.configuration.loader.publish_interval}}'
        - name: DATA_DIRECTORY
          value: '{{ .Values.configuration.loader.data_mount}}/data/load/'
        - name: DATA_BATCH_SIZE
          value: '{{ .Values.configuration.loader.batch_size}}'
        volumeMounts:
          - name: datadir
            mountPath: {{ .Values.configuration.loader.data_mount}}
      # These container runs during pod initialization
      initContainers:
      - name: install
        image: busybox
        command:
        - sh
        - -c
        - wget {{ .Values.data.datadirectory }} -O {{ .Values.configuration.loader.data_mount}}/data.zip; unzip {{ .Values.configuration.loader.data_mount}}/data.zip -d {{ .Values.configuration.loader.data_mount}}/
        volumeMounts:
        - name: datadir
          mountPath: {{ .Values.configuration.loader.data_mount}}
      dnsPolicy: Default
      volumes:
      - name: datadir
        emptyDir: {}